// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvHE3myco9Le4PVWfUviqM9UCuF-BE18',
    appId: '1:376572217238:android:c3c8613e3e1e2f67baffb7',
    messagingSenderId: '376572217238',
    projectId: 'neurodrive-5660a',
    databaseURL: 'https://neurodrive-5660a-default-rtdb.firebaseio.com',
    storageBucket: 'neurodrive-5660a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tDHgcK6pCppuzDxh1hpNWYCSrTrrJw4',
    appId: '1:376572217238:ios:612c2ce304a9c7f3baffb7',
    messagingSenderId: '376572217238',
    projectId: 'neurodrive-5660a',
    databaseURL: 'https://neurodrive-5660a-default-rtdb.firebaseio.com',
    storageBucket: 'neurodrive-5660a.firebasestorage.app',
    iosBundleId: 'com.example.neurodrive',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqTBcGmbmGpp_5jVjd_Fe4cvnmWF4re80',
    appId: '1:376572217238:web:7ad885498494fcd0baffb7',
    messagingSenderId: '376572217238',
    projectId: 'neurodrive-5660a',
    authDomain: 'neurodrive-5660a.firebaseapp.com',
    databaseURL: 'https://neurodrive-5660a-default-rtdb.firebaseio.com',
    storageBucket: 'neurodrive-5660a.firebasestorage.app',
    measurementId: 'G-T4QQBN8SBT',
  );

}